language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  keep-history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
before_script:
  - npm i -g gatsby
  - npm i
script:
  - npm run build || travis_terminate 1;
  - npm run test || travis_terminate 1;
after_success:
  - npm run deploy
  
